# DO NOT EDIT THIS FILE UNDER ANY CIRCUMSTANCES
export USERNAME=bkirinci
# export PALIP=10.23.224.213  # cpg-lab-06 / palmyra-32 (do not use)
# export PALIP=10.23.224.213
# export BOARDNAME=palmyra-32
# export PALIP=172.19.240.161
# export BOARDNAME=vek385-27
# export VEK385IP=crimini2
export VEK385IP=portobello13
# export VEK385IP=crimini5
# export VEK385IP=crimini4
# export VEK385IP=gomphus8


export AIEDBG_TARGET=xsdb://${VEK385IP}:3121

source /proj/xbuilds/HEAD_daily_latest/installs/lin64/HEAD/Vitis/settings64.sh
