// Auto-generated by aiehlc: DMA offsets for __global__ kernel 'loop_kernel'
// Chess window runtime allocates from 0x78000+; DMA offset = chess_addr - 0x70000
// in_ping at chess 0x78000 = DMA offset 0x8000
#ifndef CORE_IP_MEM
#define CORE_IP_MEM 0x8000 /* in_ping window pool alloc */
#endif
// out_ping at chess 0x78800 = DMA offset 0x8800
#ifndef CORE_OP_MEM
#define CORE_OP_MEM 0x8800 /* out_ping window pool alloc */
#endif
